### PR TITLE
fix: updated doc links

### PR DESCRIPTION
**Pull request by i-chvets**
https://github.com/canonical/kubeflow-dashboard-operator/issues/26

Summary of changes:
- Updated doc links.

### CODE REVIEW

**Review by DnPlas — CHANGES_REQUESTED** [review]
Thanks @i-chvets, few comments. Also, please change the base of this PR to point to `track/1.7` instead of `main`.

**Comment by i-chvets** [comment]
> Thanks @i-chvets, few comments. Also, please change the base of this PR to point to `track/1.7` instead of `main`.
> 
> Also, please do not forget to add the "Fixes #26" phrase in your commit so it triggers all the appropriate automation to close the issue and JIRA card.

Switched to `track/1.7`
Will add "Fixes #26" to comment when CI passes.

**Review by DnPlas — APPROVED** [review]

**Comment by DnPlas** [comment]
Thanks @i-chvets, LGTM. Remember to squash merge your commits :)

**Comment by i-chvets** [comment]
Fixes #26

**Pull request merged**
